---

- name: check authorized_keys
  stat:
    path: "{{ password_store_authorized_keys }}"
  register: t_password_store_authorized_keys

- name: configure authorized_keys
  file:
    path: "{{ password_store_authorized_keys }}"
    state: touch
    mode: '0600'
    owner: "{{ password_store_user }}"
    group: "{{ password_store_group }}"
  when: not t_password_store_authorized_keys.stat.exists
